name: kigo_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_i18n: ^0.35.1
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: 5.8.4
  flutter_svg: ^2.0.9
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  meta: ^1.10.0
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2

dev_dependencies:
  analyzer: ^5.13.0
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - images/png/
    - images/svg/
    - assets/flutter_i18n/
